package br.com.desafio.apirest.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Person")
public class Person {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private String cpf; 
	
	@DynamoDBAttribute
	private String name;
	
	@DynamoDBAttribute
	private Address address;
	
}
